// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carbon-noir/Dashboard.tsx": () => import("../components/mockups/carbon-noir/Dashboard.tsx"),
  "./components/mockups/carbon-noir/Entrance.tsx": () => import("../components/mockups/carbon-noir/Entrance.tsx")
};
